USE Test;
GO

CREATE SCHEMA app AUTHORIZATION dbo;
GO

CREATE TABLE app.TABLE_1
(
    Id INT IDENTITY(1,1) PRIMARY KEY,
    Name NVARCHAR(100) NOT NULL,
    CreatedAt DATETIME2 NOT NULL DEFAULT SYSDATETIME()
);
GO

CREATE TABLE app.TABLE_2
(
    Id INT IDENTITY(1,1) PRIMARY KEY,
    Value NVARCHAR(100) NOT NULL
)
ON TestFileGroup;
GO

CREATE SCHEMA external AUTHORIZATION dbo;
GO

CREATE TABLE external.TABLE_3
(
    Id INT IDENTITY(1,1) PRIMARY KEY,
    Comment NVARCHAR(200) NULL
);
GO

USE RZ_DB;
GO

CREATE SCHEMA rz AUTHORIZATION dbo;
GO

CREATE TABLE rz.MY_TABLE
(
    Id INT IDENTITY(1,1) PRIMARY KEY,
    Data NVARCHAR(100) NOT NULL
);
GO